### ISSUE TITLE
config flow error - setup could not be completed successfully 

### ISSUE THREAD

**Issue by FSK76** [openkfw/homeassistant_goechargerv2#2]
after saving the initial config, integration could not be loaded. Log-Message:

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/goechargerv2/__init__.py:98 
Integration: go-e Charger v2 (documentation, issues) 
First occurred: 2:35:44 PM (1 occurrences) 
Last logged: 2:35:44 PM

Error during setup of component goechargerv2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/goechargerv2/__init__.py", line 211, in async_setup
    chargers_api = _setup_apis(config, hass)
  File "/config/custom_components/goechargerv2/__init__.py", line 98, in _setup_apis
    raise ValueError(f"Missing {DOMAIN} entry in the config")
ValueError: Missing goechargerv2 entry in the config

**Comment by mmacai** [comment]
@FSK76 pushed an update, now it should be easier to add a charger via UI config flow, meaning no need to change configuration.yaml in any way.
